### ISSUE TITLE
Mailing wants {domain.address} token in the body of the html

### ISSUE THREAD

**Issue by hansrossel** [civicrm/org.civicrm.flexmailer#14]
Although we have {domain.address} in the footer message civicrm/admin/component?action=update&id=2, a mailing does not want to send until we put an extra {domain.address} in the body text. Error "Mailing cannot be sent. There are missing or invalid fields (body_html:domain.address)

**Comment by fuerst** [comment]
You may disable the check for mandatory tokens in menu Administer -> CiviMail -> CiviMail Component Settings.

**Comment by mlutfy** [comment]
Thanks @fuerst 

I think this resolves the issue? I haven't bumped into this is a while. Feel free to re-open if you think the issue persists.
