### ISSUE TITLE
Publish a 'stable' version?

### ISSUE THREAD

**Issue by JoeMurray** [civicrm/org.civicrm.flexmailer#26]
Seems to be stable for last year and half. Perhaps this could be published for auto-download?

**Comment by totten** [comment]
Generally agree, and others have given the same feedback. I'm taking another look at the PR/issue queue with an aim to marking this stable.

**Comment by nganivet** [comment]
+1, thanks @totten

**Comment by totten** [comment]
Tagged as v1.0-beta1

**Comment by eileenmcnaughton** [comment]
@mattwire - you will need to resolve this in conjunction with tagging mosaico

**Comment by mattwire** [comment]
https://github.com/civicrm/org.civicrm.flexmailer/pull/36

**Comment by mlutfy** [comment]
Closing, since we have stable releases.

**Comment by eileenmcnaughton** [comment]
Note the goal is to move this to the civicrm-core/ext repo. Not sure what steps we need other than checking it in

**Comment by mlutfy** [comment]
Opened this issue as a followup: https://lab.civicrm.org/dev/core/-/issues/1825
