### ISSUE TITLE
How do I upgrade flexmailer?

### ISSUE THREAD

**Issue by thoni56** [civicrm/org.civicrm.flexmailer#40]
I have flexmailer 0.2-alpha2 installed, but Mosaico requires higher versions. But I can't see any upgrade.

Should I just download and install on top of previous version? Remove and re-install?

**Comment by mlutfy** [comment]
Hi @thoni56, you have probably found a solution already, but for reference the releases are listed here: https://civicrm.org/extensions/flexmailer (if, at the time, it was not displayed, there must have been a problem with the extension release manager)

It should also be able to use the in-app Extension manager to update. In any case, we can install on top of the previous version.
