### ISSUE TITLE
upgrade path?

### ISSUE THREAD

**Issue by Upperholme** [civicrm/org.civicrm.flexmailer#42]
I have version 0.2-alpha5 installed currently (along with Mosaico 2.1 and CiviCRM 5.13.4). Attempting to update directly to Flexmailer v.1.1.0, by deleting the old extension files then downloading the new release to the server and unzipping, then clicking the 'Refresh' button on my extensions page, fails. Refresh just keeps running. Reloading the page leads to a white screen, and the error log reports the following fatal error:

PHP Fatal error:  Class 'Civi\\FlexMailer\\FlexMailer' not found in /home/p6/sites/default/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/CRM/Mosaico/Services.php on line 43

My PHP version is 5.6.

Swapping back to 0.2-alpha5 resolves the issue.

**Comment by MegaphoneJon** [comment]
I think this is resolved with a cache clear @Upperholme - I've seen this previously as well.

**Comment by Upperholme** [comment]
Thanks for the tip. Doesn't appear to make any difference in this case.

**Comment by Upperholme** [comment]
I'll try disabling Mosaico and then installing the updated Flexmailer...

**Comment by Upperholme** [comment]
That seemed to do the trick: disable Mosaico, install Felxmailer update, re-enable Mosaico.
