### ISSUE TITLE
Error when upgrading on Joomla - Civi\FlexMailer\Services not found

### ISSUE THREAD

**Issue by deepak-srivastava** [civicrm/org.civicrm.flexmailer#45]
Civi Upgrade throws a php 500 error when upgrading from v5.14.1 to v5.16.2.

![image](https://user-images.githubusercontent.com/3448551/63505203-06066b80-c4cb-11e9-9e0d-70d31645fcb4.png)

![image](https://user-images.githubusercontent.com/3448551/63505240-1ae2ff00-c4cb-11e9-87bd-22202fe3d7b1.png)

Clearing cache and templates_c didn't solve the problem.
But disabling the flexmailer (and mosaico because of dependency) made the upgrade work. Re-enabled after upgrade.

**Comment by andrewpthompson** [comment]
I am experiencing this with each CiviCRM upgrade, most recently when upgrading CiviCRM from 5.16.3 to 5.17.0 on Joomla. Each time the workaround has been to disable Mosaico and Flexmailer and re-enable them after the db upgrade completes.
When running the database upgrader initially it stalled with "Running task: Upgrade DB to 5.17.alpha1: SQL" being the last message displayed.
The CiviCRM log showed an additional entry after that: "Running task: Update smart groups where jcalendar fields have been converted to datepicker" (which was the last entry)
```
Sep 06 09:30:58  [info] Running task: Cleanup old files
Sep 06 09:30:58  [info] Running task: Checking extensions
Sep 06 09:30:58  [info] Running task: Begin Upgrade to 5.17.alpha1
Sep 06 09:30:58  [info] Running task: Upgrade DB to 5.17.alpha1
Sep 06 09:30:59  [info] Running task: Upgrade DB to 5.17.alpha1: SQL
Sep 06 09:30:59  [info] Running task: Update smart groups where jcalendar fields have been converted to datepicker
```
After rolling back the database to a backup I went to the database upgrade page (administrator/index.php?option=com_civicrm&task=civicrm/upgrade&reset=1) and received this error:
![image](https://user-images.githubusercontent.com/25069773/64403636-7959d100-d0b8-11e9-8f2d-1efdf823d8cf.png)
I disabled Mosaico and Flexmailer and was then able to complete the db upgrade.

**Comment by mlutfy** [comment]
Are you still running into this issue?

I used to stumble on this error sometimes as well, but it's been a while since I have seen it (it was on Drupal7; the upgrade still ran, but would give an error at the end).

**Comment by andrewpthompson** [comment]
@mlutfy I haven't seen this problem for at least a few months I think. Certainly my upgrades to 5.25.0, 5,26.1 and 5.26,2 were trouble-free. (I did have an unrelated [problem](https://lab.civicrm.org/dev/joomla/-/issues/26) with 5.23.x)

**Comment by mlutfy** [comment]
Thanks for the update. I will close this issue for now.
