### ISSUE TITLE
SMTP temp failure causes "Call to undefined method CRM_Utils_Mail_FilteredPearMailer::disconnect()"

### ISSUE THREAD

**Issue by aydun** [civicrm/org.civicrm.flexmailer#55]
See https://lab.civicrm.org/dev/core/issues/1717

Logging it here as well since it could involve changes to flexmailer and/or core.

**Comment by eileenmcnaughton** [comment]
@totten this should be closable

**Comment by mlutfy** [comment]
Closing, since the PR upstream has been merged.
