### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jitendrapurohit** [civicrm/org.civicrm.flexmailer#65]
Noticed a problem with Drupal8 + CiviCRM 5.28.2 not tracking open events on mailings sent via civimail. This is happening from past few weeks so not sure if it was after the latest security upgrade. Click tracking was done fine but open count is 0 for all the mailings. Eg -

![image](https://user-images.githubusercontent.com/5929648/91386480-b3376080-e850-11ea-86ac-52c9eb482be9.png)

Few related PRs I found while digging -

https://github.com/civicrm/org.civicrm.flexmailer/pull/56
https://github.com/civicrm/civicrm-core/pull/17312

We had the latest version v1.1.1 from https://civicrm.org/extensions/flexmailer. Updated the ext with the master version available here on github and that fixed the open tracking problem for us.

Should we have a new release on https://civicrm.org/extensions/flexmailer?

**Comment by adixon** [comment]
Curiously, it appears that there is a new release 1.1.2 on Aug 5 which is now included on my upgrade to 5.29.1.

I'm guessing that the new release is only getting published on lab.civicm.org and picked up by packagist.

It might be smart  to put a big note redirecting visitores, assuming this repo is now abandoned? Actually, I can't find the extension on lab.civicrm.ca either.

**Comment by agileware-justin** [comment]
Flexmailer is bundled in CiviCRM 5.27 and above.

Notice on this Git repo would be useful.

**Comment by adixon** [comment]
Good idea ... @mlutfy ?

**Comment by mlutfy** [comment]
Agree - I added a notice to the README on this repo, changed the github description and will archive the repo. Thanks everyone :)
